server:
  port: 9527
spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE #使用注册中心服务列表服务名动态路由，lb表示默认启用负载均衡
          predicates:
            - Path=/payment/getPaymentById/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #使用注册中心服务列表服务名动态路由，lb表示默认启用负载均衡
#          filters:
#            - AddRequestParameter=X-request-id,1024 #过滤工厂会在匹配的请求头上加上一对请求头，键为X-request-id，值为1024
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由,
#            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai] #断言,时间相匹配的进行路由
#            - Cookie=username,wyg #断言,cookie相匹配的进行路由
#            - Header=X-request-id,\d+ #断言header中包含属性名为X-request-id，值为正整数
#            - Host=localhost
#            - Method=GET

          #所有断言全为true才会进行路由

      discovery:
        locator:
          enabled: true #开启从注册中心动态路由功能（不写也可以实现根据服务名路由）

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册中心地址