server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wyinggang/SpringCloud-config.git #github地址
          search-paths:
            - SpringCloud-config #目录
      label: master


  #在config-client端配置暴露端点后还需要在github上更新后，请求http://localhost:3355/actuator/refresh接口，这样在3355上就可以不用重启获取最新配置
  #手动刷新(curl -X POST "http://localhost:3355/actuator/refresh")
  #如果有很多个配置中心客户端，会需要手动刷新多次，-----> 引入消息总线

  #rabbitmq相关配置，注意对齐，属于spring下的,引入spring cloud bus 与 rabbitmq 相关jar包，配置后，
  #就可以在更新github后，通过 curl -X POST "http://localhost:3344/actuator/bus-refresh" 通知config-server，让所有config-client更新配置
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册中心地址



#rabbitmq相关配置，暴露bus刷新的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'