server:
  port: 9002

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #注册中心地址

#设置feign客户端的超时时间（openfeign默认支持ribbon）
ribbon:
  #建立连接所用时间5s
  ReadTimeout:  5000
  #建立连接后从服务端读取到可用资源的时间5s
  ConnectTimeout: 5000

logging:
   level:
     #feign日志以什么级别监控哪个接口
     com.wyg.springcloud.feignService.FeignPaymentService: debug
